language: node_js
node_js:
  - "8"
branches:
  only:
    - develop
    - master
addons:
  sonarcloud:
    organization: "wslyvh-github"
    token:
      secure: ${SONAR_TOKEN}
before_install:
  - npm update
install:
  - npm install
  - npm install codecov -g
before_script:
  - rm -r docs
script:
  - npm run lint
  - npm run test
  - npm run doc
after_script:
  - touch ./docs/.nojekyll
after_success:
  - codecov
  - sonar-scanner
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: "docs"
  on:
    branch: master
