language: node_js
node_js:
  - "8"
branches:
  only:
    - develop
    - master
addons:
  sonarcloud:
    organization: "wslyvh-github"
    token:
      secure: ${SONAR_TOKEN}
before_install:
  - npm update
install:
  - npm install
  - npm install codecov -g
before_script:
  - rm -rf docs
script:
  - npm run lint
  - npm run test
  - npm run doc
after_success:
  - codecov
  - sonar-scanner
before_deploy:
  - touch ./docs/.nojekyll
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local_dir: "docs"
  on:
    branch: master
deploy: 
  provider: npm
  skip_cleanup: true
  api_key: ${NPM_TOKEN}
  email: ${NPM_EMAIL}
  on:
    branch: master
