language: node_js
node_js:
- '8'
branches:
  only:
  - develop
  - master
addons:
  sonarcloud:
    organization: "wslyvh-github"
    token:
      secure: ${SONAR_TOKEN}
before_install:
- npm update
install:
- npm install
- npm install codecov -g
script:
- npm run lint
- npm run test
after_success:
  - codecov
  - sonar-scanner